version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/VaultCredentialRotator/VaultCredentialRotator.csproj --verbosity m
build_script:
  # output will be in ./src/bin/Release/netcoreapp2.2/publish
  - cmd: dotnet publish ./src/VaultCredentialRotator/VaultCredentialRotator.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\VaultCredentialRotator\bin\Release\netcoreapp2.2\publish'
   name: VaultCredentialRotator
   type: zip
clone_depth: 1
#test_script:
  # restore packages for our unit tests
#  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
#  - cmd: cd tests
#  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off